#!/usr/bin/env bash
set -exuo pipefail

# build the core SDK package an all sub-packages

bash ./scripts/build

for dir in packages/*; do
    if [ -d "$dir" ]; then
        (cd "$dir" && pnpm install && pnpm build)
    fi
done
