name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: github.repository == 'anthropics/anthropic-sdk-typescript'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Check types
        run: ./scripts/lint

  build:
    name: build
    runs-on: ubuntu-latest
    if: github.repository == 'anthropics/anthropic-sdk-typescript'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Check build
        run: ./scripts/build
  test:
    name: test
    runs-on: ubuntu-latest
    if: github.repository == 'anthropics/anthropic-sdk-typescript'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Build
        run: ./scripts/build-all

      - name: Run tests
        run: ./scripts/test-all
